#!/usr/bin/env python3
"""
Assemble pipeline.py from tagged notebook cells.

Usage:
  python3 scripts/build_pipeline.py
  python3 scripts/build_pipeline.py --notebook path/to/notebook.ipynb

Cells tagged `kfp_step` become component functions.
The cell tagged `kfp_pipeline` becomes the pipeline() function.
"""
import argparse
import json
import pathlib
import re


def build_pipeline(notebook_path="notebook.ipynb"):
    nb = json.loads(pathlib.Path(notebook_path).read_text())
    step_srcs, pipeline_src = [], None
    for cell in nb["cells"]:
        if cell["cell_type"] != "code":
            continue
        tags = cell.get("metadata", {}).get("tags", [])
        src = "".join(cell["source"])
        if "kfp_step" in tags:
            step_srcs.append(src)
        elif "kfp_pipeline" in tags:
            pipeline_src = src

    if not step_srcs:
        raise RuntimeError("No cells tagged 'kfp_step' found in notebook.")
    if pipeline_src is None:
        raise RuntimeError("No cell tagged 'kfp_pipeline' found in notebook.")

    names = [
        m.group(1)
        for src in step_srcs
        for m in [re.search(r"^def (\w+)\(", src, re.MULTILINE)]
        if m
    ]

    out  = "# Generated by notebook.ipynb — do not edit manually.\n"
    out += "# Re-run scripts/build_pipeline.py (or the Build cell) to regenerate.\n\n"
    out += "from kfp import dsl\n"
    out += "from kfp import kubernetes\n\n\n"
    out += "\n\n\n".join(step_srcs)
    out += "\n\n\n"
    out += pipeline_src
    out += "\n"
    pathlib.Path("pipeline.py").write_text(out)
    print(f"Wrote pipeline.py — {len(names)} component(s): {', '.join(names)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--notebook", default="notebook.ipynb")
    args = parser.parse_args()
    build_pipeline(args.notebook)
